ALTER TABLE draws
    ADD COLUMN IF NOT EXISTS active_subscriber_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE draws
    ADD COLUMN IF NOT EXISTS total_pool_amount NUMERIC(14, 2) NOT NULL DEFAULT 0;

ALTER TABLE draws
    ADD COLUMN IF NOT EXISTS tier5_pool_amount NUMERIC(14, 2) NOT NULL DEFAULT 0;

ALTER TABLE draws
    ADD COLUMN IF NOT EXISTS tier4_pool_amount NUMERIC(14, 2) NOT NULL DEFAULT 0;

ALTER TABLE draws
    ADD COLUMN IF NOT EXISTS tier3_pool_amount NUMERIC(14, 2) NOT NULL DEFAULT 0;

ALTER TABLE draws
    ADD COLUMN IF NOT EXISTS rollover_in_amount NUMERIC(14, 2) NOT NULL DEFAULT 0;

ALTER TABLE draws
    ADD COLUMN IF NOT EXISTS rollover_out_amount NUMERIC(14, 2) NOT NULL DEFAULT 0;

ALTER TABLE draws
    ADD COLUMN IF NOT EXISTS total_charity_contribution_amount NUMERIC(14, 2) NOT NULL DEFAULT 0;
